### ISSUE TITLE
lng dist and lng build don't throw exit error codes 

### ISSUE THREAD

**Issue by ringleader3** [rdkcentral/Lightning-CLI#124]
Not sure if this is a known issue, using lng dist and lng build in a node script to subsequently update the index.html file.  When using a promise using `execa` for running lng dist I noticed that if there is an error in my js code, there isn't an error exit code on running lng dist, and infact all of the output from lng dist is piped into stderr instead of std out... 

example:
```
execa('lng', ['dist']).then(function(res) {
    // Insert script tag with adobe vendor script to index of dist folder (if it's missing)
    console.log(res)
    console.log(res.stderr);
    <--- DO STUFF--->
    console.log('Build written to ' + targetFolder)
    }).catch (function (e) {
        console.log('error case');
        console.log(e);
    });`

output:
{
  command: 'lng dist',
  exitCode: 0,
  stdout: ' \n \n \n \n \n \nundefined',
  stderr: '- Ensuring "es6" folder exists\n' +
    '✔ Ensuring "es6" folder exists\n' +
    '- Ensuring "js" folder exists\n' +
    '✔ Ensuring "js" folder exists\n' +
    '- Removing "static" folder\n' +
    '✔ Removing "static" folder\n' +
    '- Copying static assets to "es6"\n' +
    '✔ Copying static assets to "es6"\n' +
    '- Building ES6 appBundle using [esbuild] and saving to js\n' +
    ' > src/pages/paywall/index.js:235:130: error: Unexpected ","\n' +
    '    235 │ ...is._actions[this.focusRef].button.sku : this.offer.package.sku[0];,\n' +
    '        ╵                                                                      ^\n' +
    '\n' +
    '1 error\n' +
    '✖ Error while creating ES6 bundle using [esbuild] (see log)\n' +
    '(node:77138) UnhandledPromiseRejectionWarning: TypeError: PromiseReject called on non-object\n' +
    '    at reject (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
    '(node:77138) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)\n' +
    '(node:77138) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
}
- Ensuring "es6" folder exists
✔ Ensuring "es6" folder exists
- Ensuring "js" folder exists
✔ Ensuring "js" folder exists
- Removing "static" folder
✔ Removing "static" folder
- Copying static assets to "es6"
✔ Copying static assets to "es6"
- Building ES6 appBundle using [esbuild] and saving to js
 > (REDACTED): error: Unexpected ","
    235 │ (REDACTED),
        ╵                                                                      ^

1 error
✖ Error while creating ES6 bundle using [esbuild] (see log)
(node:77138) UnhandledPromiseRejectionWarning: TypeError: PromiseReject called on non-object
    at reject (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:77138) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:77138) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Build written to (name)
```

as you can see the catch block doesn't run, because the lng dist "error" doesn't supply an error exit code, and looking at the result of the lng dist command, all of the logging is piped to std err

**Comment by spsandiford** [comment]
I just ran into this same issue in my Jenkins pipeline.  There was an error in my source code and lng dist failed to compile but the return code was 0.  The pipeline stage indicated success and continued execution even though the dist directory was not created.

**Comment by sandeep-vedam** [comment]
Hey @ringmaster3,

Thanks for posting this.

In general, the error thrown at execa in one level will not be considered an error for the execa in the next level(instead it will be input(will be in .then instead of .catch) for the next level execa).

In our case, lng dist/build internally uses execa and the error is thrown by them without any issues and they are served as input for the execa that is being used in your script. 

CLI has nothing to do here. The workaround can be, in your script, parse the message thrown by the lng dist/build and then proceed accordingly.
