### ISSUE TITLE
Error while creating ES6 bundle - UnhandledPromiseRejectionWarning: TypeError: PromiseReject called on non-object

### ISSUE THREAD

**Issue by dwrobel** [rdkcentral/Lightning-CLI#51]
We're observing the following problems:
```
(node:1198) UnhandledPromiseRejectionWarning: TypeError: PromiseReject called on non-object
    at reject (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To termi
nate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The first problem is that `lng` doesn't seem to use `--unhandled-rejections=strict` option which means that bundling creation fails but remains unnoticed from the rest of the build process. We would need to have `non-zero` exit code in all that cases.

The second problem is why this actually happens?

What we're trying to do is to compile: [refapp](https://github.com/LibertyGlobal/refapp/tree/lightning) + [PR13](https://patch-diff.githubusercontent.com/raw/LibertyGlobal/refapp/pull/13.patch).

The full recipe can be found here: https://code.rdkcentral.com/r/#/c/components/generic/rdk-oe/meta-cmf-video-restricted/+/38330/2/

do_configure log:
```
DEBUG: Executing python function sysroot_cleansstate
DEBUG: Removing manifest: /data/dwrobel1/rdkv/rpi-refapp2/build-raspberrypirdkhybrefapp/tmp/sysroots/raspberrypirdkhybrefapp/sysroot-providers/refapp2
DEBUG: Removing manifest: /data/dwrobel1/rdkv/rpi-refapp2/build-raspberrypirdkhybrefapp/tmp/sysroots/raspberrypirdkhybrefapp/sysroot-providers/
DEBUG: Python function sysroot_cleansstate finished
DEBUG: Executing shell function do_configure
Using npm version : 6.14.4
npm WARN com.metrological.app.myawesomeapp@ No repository field.
npm WARN com.metrological.app.myawesomeapp@ No license field.

audited 3954 packages in 3.163s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN com.metrological.app.myawesomeapp@ No repository field.
npm WARN com.metrological.app.myawesomeapp@ No license field.

+ wpe-lightning-cli@1.4.2
updated 1 package and audited 3954 packages in 9.014s

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

DEBUG: Shell function do_configure finished
DEBUG: Executing python function do_qa_configure
DEBUG: Python function do_qa_configure finished
```

do_compile log:
```
DEBUG: Executing shell function do_compile
Using node version : v12.16.3
 
- Removing "dist" folder
✔ Removing "dist" folder
 
- Ensuring "dist" folder exists
✔ Ensuring "dist" folder exists
 
- Copying support files to "dist"
✔ Copying support files to "dist"
 
- Copying static assets to "dist"
✔ Copying static assets to "dist"
 
- Copying settings.json "dist"
✔ Copying settings.json "dist"
 
- Copying metadata.json "dist"
✔ Copying metadata.json "dist"
 
- Building ES6 appBundle and saving to "dist"
✖ Error while creating ES6 bundle (see log)
 

(node:1198) UnhandledPromiseRejectionWarning: TypeError: PromiseReject called on non-object
    at reject (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ mkdir dist/img
+ mkdir dist/cache
+ mkdir dist/fonts
+ cp -avr ./src/img/. dist/img/.
‘./src/img/./default-poster.jpg’ -> ‘dist/img/././default-poster.jpg’
‘./src/img/./movies’ -> ‘dist/img/././movies’
‘./src/img/./movies/movie_01.png’ -> ‘dist/img/././movies/movie_01.png’
‘./src/img/./movies/movie_02.png’ -> ‘dist/img/././movies/movie_02.png’
‘./src/img/./movies/movie_03.png’ -> ‘dist/img/././movies/movie_03.png’
‘./src/img/./movies/movie_04.png’ -> ‘dist/img/././movies/movie_04.png’
‘./src/img/./movies/movie_05.png’ -> ‘dist/img/././movies/movie_05.png’
‘./src/img/./movies/movie_06.png’ -> ‘dist/img/././movies/movie_06.png’
‘./src/img/./movies/movie_07.png’ -> ‘dist/img/././movies/movie_07.png’
‘./src/img/./node’ -> ‘dist/img/././node’
‘./src/img/./node/border.png’ -> ‘dist/img/././node/border.png’
‘./src/img/./posters’ -> ‘dist/img/././posters’
‘./src/img/./posters/poster_01.png’ -> ‘dist/img/././posters/poster_01.png’
‘./src/img/./posters/poster_02.png’ -> ‘dist/img/././posters/poster_02.png’
‘./src/img/./posters/poster_03.png’ -> ‘dist/img/././posters/poster_03.png’
‘./src/img/./posters/poster_04.png’ -> ‘dist/img/././posters/poster_04.png’
‘./src/img/./posters/poster_05.png’ -> ‘dist/img/././posters/poster_05.png’
‘./src/img/./posters/poster_06.png’ -> ‘dist/img/././posters/poster_06.png’
‘./src/img/./posters/poster_07.png’ -> ‘dist/img/././posters/poster_07.png’
‘./src/img/./rdk-logo.png’ -> ‘dist/img/././rdk-logo.png’
‘./src/img/./tvchannels’ -> ‘dist/img/././tvchannels’
‘./src/img/./tvchannels/1.png’ -> ‘dist/img/././tvchannels/1.png’
‘./src/img/./tvchannels/10.png’ -> ‘dist/img/././tvchannels/10.png’
‘./src/img/./tvchannels/11.png’ -> ‘dist/img/././tvchannels/11.png’
‘./src/img/./tvchannels/12.png’ -> ‘dist/img/././tvchannels/12.png’
‘./src/img/./tvchannels/13.png’ -> ‘dist/img/././tvchannels/13.png’
‘./src/img/./tvchannels/14.png’ -> ‘dist/img/././tvchannels/14.png’
‘./src/img/./tvchannels/15.png’ -> ‘dist/img/././tvchannels/15.png’
‘./src/img/./tvchannels/16.png’ -> ‘dist/img/././tvchannels/16.png’
‘./src/img/./tvchannels/17.png’ -> ‘dist/img/././tvchannels/17.png’
‘./src/img/./tvchannels/18.png’ -> ‘dist/img/././tvchannels/18.png’
‘./src/img/./tvchannels/19.png’ -> ‘dist/img/././tvchannels/19.png’
‘./src/img/./tvchannels/2.png’ -> ‘dist/img/././tvchannels/2.png’
‘./src/img/./tvchannels/20.png’ -> ‘dist/img/././tvchannels/20.png’
‘./src/img/./tvchannels/3.png’ -> ‘dist/img/././tvchannels/3.png’
‘./src/img/./tvchannels/4.png’ -> ‘dist/img/././tvchannels/4.png’
‘./src/img/./tvchannels/5.png’ -> ‘dist/img/././tvchannels/5.png’
‘./src/img/./tvchannels/6.png’ -> ‘dist/img/././tvchannels/6.png’
‘./src/img/./tvchannels/7.png’ -> ‘dist/img/././tvchannels/7.png’
‘./src/img/./tvchannels/8.png’ -> ‘dist/img/././tvchannels/8.png’
‘./src/img/./tvchannels/9.png’ -> ‘dist/img/././tvchannels/9.png’
+ cp -avr ./src/cache/. dist/cache/.
‘./src/cache/./apps.json’ -> ‘dist/cache/././apps.json’
‘./src/cache/./appsLogos’ -> ‘dist/cache/././appsLogos’
‘./src/cache/./appsLogos/default_app_collection.png’ -> ‘dist/cache/././appsLogos/default_app_collection.png’
‘./src/cache/./appsLogos/metrological.png’ -> ‘dist/cache/././appsLogos/metrological.png’
‘./src/cache/./appsLogos/spark.png’ -> ‘dist/cache/././appsLogos/spark.png’
‘./src/cache/./config.json’ -> ‘dist/cache/././config.json’
‘./src/cache/./demo-ssm’ -> ‘dist/cache/././demo-ssm’
‘./src/cache/./demo-ssm/channelsV2.json’ -> ‘dist/cache/././demo-ssm/channelsV2.json’
‘./src/cache/./demo-ssm/movies.json’ -> ‘dist/cache/././demo-ssm/movies.json’
‘./src/cache/./demo’ -> ‘dist/cache/././demo’
‘./src/cache/./demo/channelsV2.json’ -> ‘dist/cache/././demo/channelsV2.json’
‘./src/cache/./demo/movies.json’ -> ‘dist/cache/././demo/movies.json’
‘./src/cache/./eventsV2.json’ -> ‘dist/cache/././eventsV2.json’
‘./src/cache/./menu.json’ -> ‘dist/cache/././menu.json’
+ cp -avr ./src/fonts/. dist/fonts/.
‘./src/fonts/./DejaVuSerif.ttf’ -> ‘dist/fonts/././DejaVuSerif.ttf’
DEBUG: Shell function do_compile finished
```

**Comment by dwrobel** [comment]
>npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

I see more people [reporting](https://github.com/WebPlatformForEmbedded/Lightning-CLI/issues/53)  similar deprecation warnings.

**Comment by wouterlucas** [comment]
Hi @dwrobel we seem to miss a little context here. Can you explain to us what you are trying to do? Do you want to bundle the refapp and it from the Metro app store in a browser?

**Comment by dwrobel** [comment]
Basically there is a plan to rewrite the existing Spark based [refapp](https://github.com/LibertyGlobal/refapp/tree/lightning) into [Lightning base](https://patch-diff.githubusercontent.com/raw/LibertyGlobal/refapp/pull/13.patch) one.

At the moment we're struggling with bundling the application for the browser target as the `lng bundle` silently fails without providing any comprehensive explanation whether the problem is in the application's sources or in the `lng`.

We need this process in place to be able to validate incoming PRs before we can safely merge them. Actually we got stuck in the first PR.

**Comment by michielvandergeest** [comment]
Would this repo / branch (https://github.com/kathiravanltts/refapp/tree/lightning2) be the correct reference to try and reproduce / debug these issues?

**Comment by dwrobel** [comment]
>Would this repo / branch

The canonical source of the code would be to use `refapp + PR13` as given in the original report: 
>What we're trying to do is to compile: [refapp](https://github.com/LibertyGlobal/refapp/tree/lightning) + [PR13](https://patch-diff.githubusercontent.com/raw/LibertyGlobal/refapp/pull/13.patch).

**Comment by wouterlucas** [comment]
I think using Yocto to debug an webapp is rather cumbersome, most of the Lightning engineers are not specific to 1 device and never use Yocto. So if we can solve that without that constraint, that would be nice. 

What changes have been made to refapp to make it run in Lightning so far? Or is this the first step you are taking?

**Comment by dwrobel** [comment]
>What changes have been made to refapp to make it run in Lightning so far? Or is this the first step you are taking?

This is what we're trying to compile:
>> What we're trying to do is to compile: refapp + PR13.


>I think using Yocto to debug an webapp is rather cumbersome, 

I gave you the reference to the yocto recipe just to share exact environment we're using. I meant reference to source code, patches, nodejs version, list of the commands to bundle the app.

**Comment by michielvandergeest** [comment]
I checked out the source code + PR and was able to build the RefApp with minor fixes to the App code:

1) static assets (i.e. `cache`, `fonts` and `img`) are expected to be in the `static` folder and not in the `src` folder
2) change the relative path in `Utils.asset` to for the DejaVuSerif font to be simply `fonts/DejaVuSerif.ttf`
3) use `Utils.asset('cache/menu.json')` in the fetch method in `src/mainMenu/model.js` to point to the json file
